//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.20 at 11:09:40 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://springbootwstest.com/ns", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.springbootwstest.ns;
